### 1=true  0=false

player-lock: 0

blockplace:
  all-player: 1
  specific-player-false:
  -

blockbreak:
  all-player: 1
  specific-player-false:
  -

teleport:
  all-player: 1
  specific-player-false:
  -

explode:
  tnt: 1
  creeper: 1
  all: 1

spread-event: 1

blockignite-event: 1